# ./.tmuxinator.yml

name: lt
root: .

windows:
    - nvim:
          - clear
          - nvim .
    - run:
          - yarn tauri dev
    - backend:
          - cd src-tauri/
    - git:
          - clear
          - gs
