# ./.tmuxinator.yml

name: lt
root: .

windows:
    - nvim:
          - clear
          - nvim .
    - run:
          - yarn tauri dev
    - tauri backend:
          - cd src-tauri/
    - sass build:
          - sass --watch src/sass:src/css/
    - git:
          - clear
          - gs
