[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
diesel = { version = "2.0.2", features = ["sqlite"] }
dotenvy = "0.15"
inquire = "0.4.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
uuid = { version = "0.7", features = ["serde", "v4"] }
